<?php

namespace ContainerJjrx5B2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O3d7GsJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O3d7GsJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O3d7GsJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiController::store_new_reservation' => ['privates', '.service_locator.Cm6Lvsd.App\\Controller\\ApiController::store_new_reservation()', 'getApiControllerstoreNewReservationService', true],
            'App\\Controller\\ApiController::get_user_reservations' => ['privates', '.service_locator.vDru16j.App\\Controller\\ApiController::get_user_reservations()', 'getApiControllergetUserReservationsService', true],
            'App\\Controller\\ApiController::get_all_bureaux' => ['privates', '.service_locator.L6Zmc6U.App\\Controller\\ApiController::get_all_bureaux()', 'getApiControllergetAllBureauxService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiController:store_new_reservation' => ['privates', '.service_locator.Cm6Lvsd.App\\Controller\\ApiController::store_new_reservation()', 'getApiControllerstoreNewReservationService', true],
            'App\\Controller\\ApiController:get_user_reservations' => ['privates', '.service_locator.vDru16j.App\\Controller\\ApiController::get_user_reservations()', 'getApiControllergetUserReservationsService', true],
            'App\\Controller\\ApiController:get_all_bureaux' => ['privates', '.service_locator.L6Zmc6U.App\\Controller\\ApiController::get_all_bureaux()', 'getApiControllergetAllBureauxService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiController::store_new_reservation' => '?',
            'App\\Controller\\ApiController::get_user_reservations' => '?',
            'App\\Controller\\ApiController::get_all_bureaux' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiController:store_new_reservation' => '?',
            'App\\Controller\\ApiController:get_user_reservations' => '?',
            'App\\Controller\\ApiController:get_all_bureaux' => '?',
        ]);
    }
}
