<?php

namespace ContainerJjrx5B2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetAllBureauxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L6Zmc6U.App\Controller\ApiController::get_all_bureaux()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L6Zmc6U.App\\Controller\\ApiController::get_all_bureaux()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bureau_repository' => ['privates', 'App\\Repository\\BureauRepository', 'getBureauRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'bureau_repository' => 'App\\Repository\\BureauRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ApiController::get_all_bureaux()', $container);
    }
}
