<?php

namespace Container4rh4Xnj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerstoreNewReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cm6Lvsd.App\Controller\ApiController::store_new_reservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cm6Lvsd.App\\Controller\\ApiController::store_new_reservation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation_repository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'reservation_repository' => 'App\\Repository\\ReservationRepository',
        ]))->withContext('App\\Controller\\ApiController::store_new_reservation()', $container);
    }
}
