<?php

namespace Container4rh4Xnj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetUserReservationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vDru16j.App\Controller\ApiController::get_user_reservations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vDru16j.App\\Controller\\ApiController::get_user_reservations()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation_repository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'reservation_repository' => 'App\\Repository\\ReservationRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ApiController::get_user_reservations()', $container);
    }
}
